-- AlterTable
ALTER TABLE `Tenant` MODIFY COLUMN `planoSaaS` ENUM('BASICO', 'INTERMEDIARIO_VENDAS', 'INTERMEDIARIO_AGENDA', 'PRO', 'ENTERPRISE') NOT NULL DEFAULT 'BASICO';

-- CreateTable
CREATE TABLE `PlanoPreco` (
    `plano` ENUM('BASICO', 'INTERMEDIARIO_VENDAS', 'INTERMEDIARIO_AGENDA', 'PRO', 'ENTERPRISE') NOT NULL,
    `nome` VARCHAR(100) NOT NULL,
    `valorMensal` DECIMAL(10, 2) NOT NULL,
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`plano`)
) DEFAULT CHARACTER SET utf8mb4;
