-- AlterTable
ALTER TABLE `Agendamento` MODIFY COLUMN `formaPagamento` ENUM('CARTAO', 'PIX', 'DINHEIRO', 'PLANO', 'CARRO_TROCA', 'CARRO_TROCA_FINANCIAMENTO') NULL;

-- AlterTable
ALTER TABLE `Produto` ADD COLUMN `valorCompra` DECIMAL(10, 2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `ItemVenda` ADD COLUMN `formaPagamento` ENUM('CARTAO', 'PIX', 'DINHEIRO', 'PLANO', 'CARRO_TROCA', 'CARRO_TROCA_FINANCIAMENTO') NULL;
